-- CreateTable
CREATE TABLE "RawOmnix" (
    "id" SERIAL NOT NULL,
    "ticket_id" INTEGER,
    "remark" TEXT,
    "subject" TEXT,
    "priority_id" INTEGER,
    "priority_name" TEXT,
    "ticket_status_id" INTEGER,
    "ticket_status_name" TEXT,
    "unit_id" INTEGER,
    "unit_name" TEXT,
    "informant_id" TEXT,
    "informant_name" TEXT,
    "informant_hp" TEXT,
    "informant_email" TEXT,
    "customer_id" TEXT,
    "customer_name" TEXT,
    "customer_hp" TEXT,
    "customer_email" TEXT,
    "date_origin_interaction" TIMESTAMP(3),
    "date_start_interaction" TIMESTAMP(3),
    "date_open" TIMESTAMP(3),
    "date_close" TIMESTAMP(3),
    "date_last_update" TIMESTAMP(3),
    "date_created_at" TIMESTAMP(3),
    "date_pickup_interaction" TIMESTAMP(3),
    "date_end_interaction" TIMESTAMP(3),
    "date_first_pickup_interaction" TIMESTAMP(3),
    "date_first_response_interaction" TIMESTAMP(3),
    "is_escalated" TEXT,
    "created_by_id" INTEGER,
    "created_by_name" TEXT,
    "updated_by_id" INTEGER,
    "updated_by_name" TEXT,
    "channel_id" INTEGER,
    "channel_name" TEXT,
    "session_id" TEXT,
    "category_id" INTEGER,
    "category_name" TEXT,
    "mainCategory" TEXT,
    "category" TEXT,
    "subCategory" TEXT,
    "detailSubCategory" TEXT,
    "detailSubCategory2" TEXT,
    "sla" TEXT,
    "sla_second" INTEGER,
    "waitingTime" TEXT,
    "serviceTime" TEXT,
    "responseTime" TEXT,
    "handlingTime" TEXT,
    "duration" TEXT,
    "acw" TEXT,
    "account" TEXT,
    "account_name" TEXT,
    "informant_member_id" TEXT,
    "customer_member_id" TEXT,
    "sentiment_incoming" TEXT,
    "sentiment_outgoing" TEXT,
    "sentiment_all" TEXT,
    "feedback" TEXT,
    "sentiment_service" TEXT,
    "parent_id" TEXT,
    "count_merged" INTEGER,
    "source_id" INTEGER,
    "source_name" TEXT,
    "contact" JSONB,
    "survey_name" TEXT,
    "interaction_additional_info" JSONB,
    "survey_id" TEXT,
    "respondent_id" TEXT,
    "ticket_id_old" TEXT,
    "ticket_perusahaan" TEXT,
    "ticket_Amount" TEXT,
    "ticket_Remedy_NO" TEXT,
    "ticket_IT/AO" TEXT,
    "ticket_Project" TEXT,
    "ticketId_masking" TEXT,
    "informant_nama_corp" TEXT,
    "customer_nama_corp" TEXT,
    "date_pending" TIMESTAMP(3),
    "date_resolve" TIMESTAMP(3),
    "date_eskalasi ebo" TIMESTAMP(3),
    "date_eskalasi it" TIMESTAMP(3),
    "date_eskalasi no" TIMESTAMP(3),
    "date_eskalasi" TIMESTAMP(3),
    "date_menunggu" TIMESTAMP(3),
    "partner" TEXT,
    "approval billco" TEXT,
    "customer_instagram_id" TEXT,
    "customer_phone" TEXT,
    "customer_facebook_id" TEXT,

    CONSTRAINT "RawOmnix_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RawOmnix_ticket_id_key" ON "RawOmnix"("ticket_id");
